#!/usr/bin/env fish
while true
    read -l sentinel
    if test "$sentinel" = kill
        exit 0
    end

    read -l runtype

    # Read lines until the sentinel is found again
    set code_to_run ""
    while read -l line
        if test "$line" = "$sentinel"
            break
        end
        set -a code_to_run $line
    end

    if test "$runtype" = r
        eval $code_to_run
    else if test "$runtype" = .p
        fish_prompt
    else
        echo -n "fish launcher does not implement msg: '$runtype'"
    end

    # Print the sentinel to signal completion
    echo
    echo "$sentinel"
end
