#!/usr/bin/env julia
session_module = Module()

function julia_main(_)
    while !eof(stdin)
        sentinel = strip(readline(stdin))
        if sentinel == "kill"
            exit(0)
        end
        isempty(sentinel) && break

        runtype = strip(readline(stdin))

        code_to_run = IOBuffer()
        while !eof(stdin)
            line = readline()
            if strip(line) == sentinel
                break
            else
                println(code_to_run, line)
            end
        end


        code = String(take!(code_to_run))

        code_string = if runtype == "r"
            "Base.show(stdout, \"text/plain\", $(code))"
        elseif runtype == "t"
            code = "println(typeof($(code)))"
        elseif runtype == "e"
            code
        else
            "print(\"Not implemented\")"
        end


        try
            include_string(session_module, code_string)
        catch e
            Base.showerror(stdout, e, Base.catch_backtrace())
        finally
            println()
            println(sentinel)
            flush(stdout)
        end
    end
    return
end

(@main)(a) = julia_main(a)
