#!/usr/bin/env python3

import sys
import traceback

session_globals = {}

while True:
    sentinel = sys.stdin.readline().strip()
    if sentinel == "kill":
        sys.exit(0)

    code_to_run = ""
    runtype = sys.stdin.readline()
    while True:
        line = sys.stdin.readline()
        if line.strip() == sentinel:
            break
        else:
            code_to_run += line

    try:
        if runtype == "e":
            compiled_code = compile(code_to_run, '<stdin>', 'exec')
            exec(compiled_code, session_globals)
        elif runtype == "r":
            compiled_code = compile(code_to_run, '<stdin>', 'exec')
            print(eval(compiled_code, session_globals))
        else:
            print("Not implemented")
    except Exception:
        traceback.print_exc(file=sys.stdout)

    finally:
        print(sentinel)
        sys.stdout.flush()
print()
