#!/usr/bin/env python3

import sys
import traceback

session_globals = {}

while True:
    sentinel = sys.stdin.readline().strip()
    if sentinel == "kill":
        break
    if not sentinel:
        break

    code_to_run = ""
    while True:
        line = sys.stdin.readline()
        if line.strip() == sentinel:
            break
        else:
            code_to_run += line

    try:
        compiled_code = compile(code_to_run, '<stdin>', 'exec')
        exec(compiled_code, session_globals)

    except Exception:
        traceback.print_exc(file=sys.stdout)

    finally:
        print(sentinel)
        sys.stdout.flush()
print()
