#!/usr/bin/env sh

# Start an interactive shell, which is crucial for it to not exit immediately.
# The `-s` flag reads commands from standard input.
/bin/sh -i -s 2>&1 <<'EOF'
while true; do
    # Read the sentinel value
    read -r sentinel
    if [ "$sentinel" = "kill" ]; then
        exit 0
    fi

    # Read lines until the sentinel is found again
    code_to_run=""
    read -r runtyp
    while read -r line; do
        if [ "$line" = "$sentinel" ]; then
            break
        fi
        code_to_run="$code_to_run$line\n"
    done

    if [ "$runtyp" = "r"]; then
        eval "$code_to_run"
    else
        echo "Not implemented"
    fi

    # Print the sentinel to signal completion
    printf "%s\n" "$sentinel"

done
EOF
